{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mirai
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mirai_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mirai/mirai_{{ version }}.tar.gz
  sha256: bc54ea155e9d45e0be2fd1dfdf256fafc742177d638078824231d21f5fe6035b

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-nanonext >=0.12.0

  run:
    - r-base
    - r-nanonext >=0.12.0

test:
  commands:
    - $R -e "library('mirai')"           # [not win]
    - "\"%R%\" -e \"library('mirai')\""  # [win]

about:
  home: https://shikokuchuo.net/mirai/
  dev_url: https://github.com/shikokuchuo/mirai/
  license: GPL-3.0-or-later
  summary: Lightweight parallel code execution and distributed computing. Designed for simplicity, a 'mirai' evaluates an R expression asynchronously, on local or network resources, resolving automatically upon completion. Efficient scheduling over fast inter-process communications or secure TLS connections over TCP/IP,
    built on 'nanonext' and 'NNG' (Nanomsg Next Gen).
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf

# Package: mirai
# Type: Package
# Title: Minimalist Async Evaluation Framework for R
# Version: 0.12.1
# Description: Lightweight parallel code execution and distributed computing. Designed for simplicity, a 'mirai' evaluates an R expression asynchronously, on local or network resources, resolving automatically upon completion. Efficient scheduling over fast inter-process communications or secure TLS connections over TCP/IP, built on 'nanonext' and 'NNG' (Nanomsg Next Gen).
# Authors@R: c(person(given = "Charlie", family = "Gao", role = c("aut", "cre"), email = "charlie.gao@shikokuchuo.net", comment = c(ORCID = "0000-0002-0750-061X")), person(given = "Hibiki AI Limited", role = "cph"))
# License: GPL (>= 3)
# BugReports: https://github.com/shikokuchuo/mirai/issues
# URL: https://shikokuchuo.net/mirai/, https://github.com/shikokuchuo/mirai/
# Encoding: UTF-8
# Depends: R (>= 3.5)
# Imports: nanonext (>= 0.12.0)
# Enhances: parallel, promises
# Suggests: knitr, markdown
# VignetteBuilder: knitr
# RoxygenNote: 7.3.1
# NeedsCompilation: no
# Packaged: 2024-02-02 08:04:02 UTC; cg334
# Author: Charlie Gao [aut, cre] (<https://orcid.org/0000-0002-0750-061X>), Hibiki AI Limited [cph]
# Maintainer: Charlie Gao <charlie.gao@shikokuchuo.net>
# Repository: CRAN
# Date/Publication: 2024-02-02 08:30:02 UTC
